# Generated by Django 4.2.6 on 2023-10-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MainApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="prim",
            field=models.TextField(default="Базовое описание", max_length=100),
        ),
    ]
